services:
  flowerstoreapp:
    build: .
    hostname: flowerstorewebapp
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      mysql_server:
        condition: service_healthy

  mysql_server:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=flowerstore-db'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=secretpwd'
      - 'MYSQL_ROOT_PASSWORD=rootpwd'
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-uuser",
          "-ppwd",
          "-h",
          "localhost",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
  phpmyadmin:
    image: phpmyadmin:5.2.0
    container_name: PhpMyAdmin
    links:
      - mysql_server
    restart: always
    ports:
      - 5013:80
    environment:
      - PMA_ARBITRARY=1

#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
